import Foundation

enum GameCatalog {
    static let all: [Game] = [
        Game(id: "belote", name: "Belote", category: "cartes", symbol: "suit.club.fill",
             engine: .contractPoints, isTeamGame: true, defaultTarget: 501, higherWins: true,
             rules: "Le camp qui prend s'engage à faire au moins 82 des 162 points en jeu (100 en cas de belote annoncée). S'il échoue, tous les points vont à la défense. Premier camp à l'objectif gagne."),
        Game(id: "coinche", name: "Coinche", category: "cartes", symbol: "suit.spade.fill",
             engine: .contractPoints, isTeamGame: true, defaultTarget: 1000, higherWins: true,
             rules: "Comme la belote, mais l'annonce est un contrat chiffré (80 à 160, ou capot) que l'adversaire peut coincher (×2) voire surcoincher (×4). Le camp qui prend doit atteindre son contrat aux points, sous peine de tout perdre."),
        Game(id: "tarot", name: "Tarot", category: "cartes", symbol: "wand.and.stars",
             engine: .contractPoints, isTeamGame: false, defaultTarget: 500, higherWins: true,
             rules: "Le preneur annonce prise, garde, garde sans ou garde contre et doit réunir un nombre de points dépendant de ses bouts (oudlers). Poignée et petit au bout apportent des bonus. Le total d'une donne est toujours nul."),
        Game(id: "papayoo", name: "Papayoo", category: "societe", symbol: "die.face.5.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 1000, higherWins: false,
             rules: "Jeu à levées où chaque carte négative (dames, valets de cœur, 8 de trèfle...) rapporte des points de pénalité au joueur qui la remporte. Le moins de points possible gagne."),
        Game(id: "rami", name: "Rami", category: "cartes", symbol: "rectangle.on.rectangle",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 500, higherWins: false,
             rules: "À chaque manche, les joueurs qui n'ont pas gagné comptent les points des cartes qu'il leur reste en main. Le score cumulé le plus bas à l'objectif gagne."),
        Game(id: "uno", name: "Uno", category: "societe", symbol: "square.stack.3d.up.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 500, higherWins: true,
             rules: "Le gagnant d'une manche marque les points des cartes restées en main de ses adversaires. Premier à l'objectif, le score cumulé le plus haut gagne."),
        Game(id: "skyjo", name: "Skyjo", category: "societe", symbol: "star.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 100, higherWins: false,
             rules: "Additionnez les valeurs de vos cartes visibles à la fin de chaque manche. Le joueur avec le score cumulé le plus bas à l'objectif remporte la partie."),
        Game(id: "scrabble", name: "Scrabble", category: "societe", symbol: "textformat.abc",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 0, higherWins: true,
             rules: "Notez le score de chaque joueur à la fin de chaque tour. Le total le plus élevé en fin de partie gagne."),
        Game(id: "flechettes", name: "Fléchettes", category: "sport", symbol: "target",
             engine: .countdown, isTeamGame: false, defaultTarget: 501, higherWins: false,
             rules: "Chaque joueur part de 501 et retire les points marqués à chaque volée. Interdit de finir sur 1 ; une volée qui dépasse ou laisse 1 point est annulée (bust). Premier à 0 gagne."),
        Game(id: "petanque", name: "Pétanque", category: "sport", symbol: "circle.circle",
             engine: .mancheWinner, isTeamGame: true, defaultTarget: 13, higherWins: true,
             rules: "Chaque mène rapporte des points à l'équipe la plus proche du cochonnet. Première équipe à 13 points gagne la partie."),
        Game(id: "billard", name: "Billard", category: "sport", symbol: "circle.grid.cross.fill",
             engine: .mancheWinner, isTeamGame: false, defaultTarget: 5, higherWins: true,
             rules: "Comptez les manches remportées. Premier joueur à 5 manches gagne le match."),
        Game(id: "yams", name: "Yam's", category: "des", symbol: "dice.fill",
             engine: .gridScore, isTeamGame: false, defaultTarget: 0, higherWins: true,
             rules: "Remplissez les 13 catégories de la grille au fil des lancers de dés. Un bonus de 35 points est offert si la partie supérieure atteint 63. Le plus gros total gagne."),
        Game(id: "421", name: "421", category: "des", symbol: "dice",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 0, higherWins: false,
             rules: "Chaque perdant charge des jetons dans la cave selon sa combinaison de dés. Une fois la cave vide, les jetons circulent entre joueurs : le premier à s'en délester gagne."),
        Game(id: "manille", name: "Manille", category: "cartes", symbol: "suit.diamond.fill",
             engine: .cumulativePoints, isTeamGame: true, defaultTarget: 500, higherWins: true,
             rules: "Jeu de plis par équipes de deux où la manille (le 10) et l'as valent le plus de points. Comptez les points remportés à chaque donne ; premier camp à l'objectif gagne."),
        Game(id: "backgammon", name: "Backgammon", category: "des", symbol: "checkerboard.rectangle",
             engine: .mancheWinner, isTeamGame: false, defaultTarget: 7, higherWins: true,
             rules: "Comptez les parties gagnées, en tenant compte du cube de doublement le cas échéant. Premier joueur à 7 points de match gagne."),
        Game(id: "bowling", name: "Bowling", category: "sport", symbol: "figure.bowling",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 0, higherWins: true,
             rules: "Notez le score final affiché par la piste (ou calculé manuellement) après les 10 frames de chaque partie. Le plus haut score gagne."),
        Game(id: "poker", name: "Poker", category: "cartes", symbol: "circle.grid.2x2.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 0, higherWins: true,
             rules: "Suivez l'évolution du tapis de jetons de chaque joueur au fil des mains (entrez la variation à chaque étape). Le plus gros tapis à la fin de la session gagne."),
        Game(id: "dominos", name: "Dominos", category: "societe", symbol: "rectangle.split.2x1.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 100, higherWins: false,
             rules: "À chaque manche, les joueurs qui n'ont pas gagné comptent les points des dominos qu'il leur reste en main. Le score cumulé le plus bas à l'objectif gagne."),
        Game(id: "millebornes", name: "Mille Bornes", category: "cartes", symbol: "car.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 5000, higherWins: true,
             rules: "Notez le total de points (bornes parcourues, primes et coups fourrés) marqué par chaque joueur à la fin de chaque manche. Premier à l'objectif gagne."),
        Game(id: "molkky", name: "Mölkky", category: "sport", symbol: "cylinder.fill",
             engine: .cumulativePoints, isTeamGame: false, defaultTarget: 50, higherWins: true,
             rules: "Lancez le mölkky pour faire tomber les quilles : une seule quille abattue rapporte son numéro, plusieurs quilles rapportent leur nombre. Il faut atteindre exactement 50 ; un dépassement fait retomber le score à 25."),
    ]

    static func game(id: String) -> Game? { all.first { $0.id == id } }

    static let categories: [(key: String, label: String)] = [
        ("all", "Tous"), ("cartes", "Cartes"),
        ("societe", "Société"), ("sport", "Sport"),
        ("des", "Dés"),
    ]
}
